# This is a basic workflow to help you get started with Actions

name: Demo 7 - Environments

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # ###################################################
  deploy_dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to DEV
    environment: DEV
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo My deploy steps
        
  #####################################################   
  
  deploy_qa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to QA
    environment: QA
    needs: deploy_dev
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo My deploy steps
        
  ####################################################    
  
  deploy_prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to PROD
    environment: PROD
    needs: deploy_qa
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo My deploy steps

      
