name: Demo 8 - CallReusable

on:
  workflow_dispatch:
    inputs:
      someInput:
        type: text
        required: true
        description: Enter the PIM ID
        default: "0"
      someChoice:
        type: choice
        options:
          - Left
          - Right
  
  
jobs:

  caller-job:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "Job from caller workflow"
          echo ${{ github.event.inputs.someInput }}
      
  reusable-job:
    uses: ./.github/workflows/reusable.yml
    needs: caller-job
    # uses: djredman99/github-intro-to-actions-demo/.github/workflows/reusable.yml@${{github.ref}}
    
  #reusable-2:
  #  uses: ./.github/workflows/dotnet/reuse.yml
    
