name: Demo 12 - Dynamic Matrix

on: [workflow_dispatch]

jobs:
  build-dynamic:
    if: false
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dynamic-matrix.outputs.matrix }}
    steps:
      - run: echo "matrix"="[ 'resourcegroup', 'keyvault', 'storageaccount' ]" >> $GITHUB_OUTPUT
        id: dynamic-matrix 

  matrix-job:
    if: false
    runs-on: ubuntu-latest
    needs: build-dynamic
    strategy:
      matrix: 
        resource: ${{ fromJSON(needs.build-dynamic.outputs.matrix)}}
    
    steps:
      - if: true
        run: echo ${{ needs.build-dynamic.outputs.matrix }}
        
      - if: true
        run: echo "${{ matrix.resource }}"

  build-dynamic-2:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dynamic-matrix.outputs.matrix }}
    steps:
      - run: |
          matrix="["
          matrix+="'resourcegroup',"
          matrix+="'keyvault',"
          matrix+="'vnet'"
          matrix+="]"
          
          echo $matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        id: dynamic-matrix 

  matrix-job-2:
    if: true
    runs-on: ubuntu-latest
    needs: build-dynamic-2
    strategy:
      matrix: 
        resource: ${{ fromJSON(needs.build-dynamic-2.outputs.matrix)}}
    
    steps:
      - if: true
        run: echo ${{ needs.build-dynamic.outputs.matrix }}
        
      - if: true
        run: echo "${{ matrix.resource }}"
