name: Demo 15 - GitHub App

on: workflow_dispatch

jobs:
  use-gh-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo ${{ vars.APP_ID }}

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: djredman99

      - uses: actions/checkout@v2
        with:
          repository: some-other-repo
          token: ${{ steps.app-token.outputs.token }}

      




