name: Run job if Debug is ON

on: workflow_dispatch

jobs:
  debug-job:
    runs-on: ubuntu-latest
    if: ${{ vars.ACTIONS_STEP_DEBUG == 'true' }}
    steps:
      - name: Debugging enabled
        run: echo "Debugging is enabled"
