name: ENV Variables

on:
  workflow_dispatch:

env:
  #OPENSHIFT_NAMESPACE: ${{ format('{0}_{1}', vars.OS_NAMESPACE, vars.OS_ENVIRONMENT)}}
  CALL_STACK: ""
  # ****** CANNOT DO *******
  # OS_NAMESPACE: abc
  # OS_ENVIRONMEN: 123
  # MY_ENV: ${{ format('{0}_{1}', env.OS_NAMESPACE, env.OS_ENVIRONMENT)}}

jobs:

  job1:

    runs-on: ubuntu-latest
    steps:
      #- run: echo ${{ env.OPENSHIFT_NAMESPACE }}
      - run: echo "CALL_STACK=$CALL_STACK,workflow1" >> $GITHUB_ENV
      - run: echo $CALL_STACK
