name: ENV Variables

on:
  workflow_dispatch:

env:
  OPENSHIFT_NAMESPACE: ${{ format('{0}_{1}', vars.OS_NAMESPACE, vars.OS_ENVIRONMENT)}}

jobs:

  job1:

    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.OPENSHIFT_NAMESPACE }}
