name: My Reusable Workflow

on:
  workflow_call:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow job1"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow job2"
