name: My Reusable Workflow

on:
  workflow_call:
    inputs:
      some_var:
        description: Hey
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow job1"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" 
      - run: aws login --secret ${{ secrets.aws_secret }}
        
  
  reusable-job2:
    uses: ./.github/workflows/reusable2.yml
    needs: job1
