name: My Reusable Workflow

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow job1"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" 
        
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow job2"
