# This is a basic workflow to help you get started with Actions

name: Demo 9 - Handling Failures

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: exit 1
  
  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    if: ${{ failure() }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "still running"
        if: ${{ failure() }}
