name: Test Shell Variables Between Run Statements

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export DAN="Hey Dan"
          echo $DAN
          
          name="Dan"
          echo $name

          pwd
          mkdir Dan
          cd Dan
          pwd

      - run: |    
          echo "-=== SHOWING VALUES ===-"
          echo $DAN
          echo $name
          echo "-=== END SHOWING VALUES ===-"
          echo "-=== Showing Path ===-"
          pwd

